[project]
name = "finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.9.0",
    "unsloth[colab-new]",
]

[tool.uv.sources]
unsloth = { git = "https://github.com/unslothai/unsloth.git" }
